### ISSUE TITLE
Hangs on await doc.end() until timeout

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#102]
I'm using commit 0a1fb0c
```js
module.exports = async function createMailingLabelsPdf(data, req) {
  let doc = new pdfjs.Document(avery5160.document);
  let table = doc.table(avery5160.table);
  let row = table.row(avery5160.row);
  let numColumns = avery5160.table.widths.length;
  // more code here... 

  let defaults = req.tags.reduce(function (all, item) {
    if (item.value && !all[item.key]) {
      all[item.key] = item.value;
    }
    return all;
  }, {});

  data.forEach(function (item, index) {
    // code here

    row.cell(content, avery5160.cell);

    // Create new row after every third column (3 column setup)
    if ((index + 1) % numColumns === 0) {
      row = table.row(avery5160.row);
    }
  });

  await doc.end(); // <--- hangs here, no error

  return doc.asBuffer();
};
```

**Comment by rkusa** [comment]
Document is a readable stream, and if there is nothing reading from it, `await doc.end()` will unfortunately hang. In this example, when using `doc.asBuffer()`, there is no need for calling `end()`, since it is handled by `asBuffer`.
Anyway there is definitely a UX problem here. I added some notes to the documentation (though they could be improved).
Btw, the recommended way of sending/saving the PDF with 2.x is to pipe the document into a stream (file stream, http response stream), e.g.:

```js
doc.pipe(fs.createWriteStream('output.pdf'))
await doc.end()
```

Piping the document is the zero-copy approach (whole PDF is not saved to memory and then copied to the file/http response), since the PDF is generated step by step and each step waits until something (a write stream) is reading from the document.

**Comment by knownasilya** [comment]
Thanks for the clarification! I'll make sure to use streaming once 2.1 lands 👍
