### ISSUE TITLE
Ensure number of page is even

### ISSUE THREAD

**Issue by hluz** [rkusa/pdfjs#113]
Thanks for all your work! One question: Any idea on how to ensure that the total number of pages in a generated document is eve? (i.e.,  add a page break if number of pages is going to be an odd number?)

**Comment by rkusa** [comment]
Hi, I am currently only on my phone so a proper answere night have to wait about a week. There is currently no public API available for this use case. From the top of my head the following private API might work:

```
await doc._next() // process all pending fragments like tables, texts etc
if (doc._pages.lenght % 2 !== 0) {
  doc.pageBreak()
}
```

Again, just from the top of my head, so might not work. But I‘ll get to you in about a week.

**Comment by hluz** [comment]
Hey, thanks for the quick response... the `await doc._endPage()` does the trick so that `doc._pages.length` gets the number of pages correctly. 

However, `doc.pageBreak()` adds 2 empty pages!?? (Something like `doc.text('empty page',{ textAlign: 'center' })` instead of `doc.pageBreak()` works to add an additional page)

**Comment by rkusa** [comment]
Ok, there some more parts to it. A working example can be found here: https://github.com/rkusa/pdfjs/blob/bc6cf4c9ff5695170d18ce0a0380c7d1a0594014/test/pdfs/issue/issue-113-even-pages.js

You saw two pages since `pageBreak()` expects a page it could add the page break, too. If there is no page, because we called `_endPage`, it will create a new one + add a page break = two pages 🙈

**Comment by hluz** [comment]
Nice. Thanks!

**Comment by rkusa** [comment]
Follow up can be found here #118
