### ISSUE TITLE
[Question] PDF/X and CMYK support

### ISSUE THREAD

**Issue by ArturJS** [rkusa/pdfjs#200]
@rkusa Thanks a lot for the great library!
I'm curious, does this library have support of __PDF/X__ format as well as __CMYK__ on it?
Thanks!

**Comment by rkusa** [comment]
Hi @ArturJS, good question. Since I don't use this library to produce PDFs for printing purposes, I never really investigated PDF/X, yet.

CMYK is unfortunately not well supported yet. `pdfjs` uses RGB (or more specifically the `sRGB_IEC61966-2-1_black scaled` ICC color space) [by default](https://github.com/rkusa/pdfjs/blob/master/lib/document.js#L110-L121). 

I guess at least the following steps would be necessary to get a CMYK PDF from `pdfjs`:

- manually override `this._colorSpace` with a CMYK color space (or add an option to configure it)
- add support for CMYK JPEGs ([looks like pdfjs currently only supports RGB and Greyscale JPEGs](https://github.com/rkusa/pdfjs/blob/master/lib/image/jpeg.js#L39-L47))
- update text/table/... options to accept CMYK colors

**Comment by ArturJS** [comment]
@rkusa Wow, thanks for the information!
That's really great that there's still a chance to make this up and running regardless of the current lack of support in [pdfjs](https://github.com/rkusa/pdfjs) itself.
I'll try to investigate this further.
Thanks!
