### ISSUE TITLE
Catch current Y value

### ISSUE THREAD

**Issue by hugodion** [rkusa/pdfjs#255]
Hi !
How can I catch the current cursor's Y value and increment it before applying it to a cell ?
Like:
![image](https://user-images.githubusercontent.com/36448889/121534412-32a4b380-c9cf-11eb-8d37-2aced30eb029.png)
Thanks for you time and help :)

**Comment by rkusa** [comment]
Hi,

you could simply omit the `y` coordinate and use a `paddingTop` of `10` instead:

```
doc.cell({x: 315, paddingTop: 10})
```

This will simply continue at your current `y` position.

There is a `doc._cursor.y` but I don't recommend using it, because it is an internal API and since the PDF is created asynchronously, it might not reflect value you expect at the time of reading it.

**Comment by hugodion** [comment]
Great thanks !
This is what I was looking for.
Cheers ! :)
