### ISSUE TITLE
Downscale images in external PDF

### ISSUE THREAD

**Issue by wildhart** [rkusa/pdfjs#311]
It would be really handy if there was a way to reduce the DPI and or jpeg quality of external reports as I combine them into a PDF.

I'm using this simple code to combine PDFs from external sources:
```ts
    async appendPdfUrl(outputDoc: pdfjs.Document, pdfUrl: string) {
        const buffer = await downloadExternalReport(pdfUrl);
        const doc = new pdfjs.ExternalDocument(buffer);
        outputDoc.addPagesOf(doc);
        return doc.pageCount;
    }
```
Then I have to send the combined PDF to a 3rd party API.  Problem is, sometimes the PDF is too big and the API rejects it.

None of the options to `new pdfjs.Document()` or `new pdfjs.ExternalDocument(buffer)` seem to allow any options for DPI or quality.

Would this even be theoretically possible?

**Comment by rkusa** [comment]
> Would this even be theoretically possible?

No, not with the way `pdfjs` works I am afraid. When combining PDFs, `pdfjs` doesn't understand the external PDF. It just recursively walks all PDF objects and copies them over. During that, it doesn't know which object respresents an image – which is why don't see this ever landing in `pdfjs` (though I agree that you have a valid use-case there).
