### ISSUE TITLE
REPL

### ISSUE THREAD

**Issue by rafis** [rkusa/pdfjs#59]
Is it possible to create a complementary project - REPL, which will have two windows: in left window a user enters javascript code and last line can be `return doc.render();`, in right window a PDF will be rendered using `mozilla/pdf.js` for example. The code from left window should be periodically evaluated, if no errors then update the right window with new PDF. And perhaps it will be wise to place project to the Github Pages (github.io) free hosting because it is fully client-side project.

**Comment by rkusa** [comment]
Hi, thanks for your feedback! This is indeed possible! For non-IE browser, PDFs could also be displayed using an iframe, instead of `pdf.js`, as done here `http://ma.rkusa.st/pdfjs/`. On this page, the PDF is also already rendered on the client-side. The project page is  on github.io (just aliased to my own domain).
Unfortunately, I am probably not going to implement this REPL myself soon, sorry. Because, I am currently investing all the pdfjs-time I have, into rethinking some parts of the implementation. However, I am currently having tough times finding a good and performant streaming table algorithm (non-streaming was easy) 😕

**Comment by rkusa** [comment]
Basic version is implemented: http://pdfjs.rkusa.st/
