### ISSUE TITLE
could not able to add the dependency in my application

### ISSUE THREAD

**Issue by barindam** [rkusa/pdfjs#63]
const pdf = require('pdfjs');  --- line no 1
Getting error on the very first line.

Error:--
node_modules/pdfjs/lib/document.js:259
  async _startPage() {
        ^^^^^^^^^^

I install this package by "npm install pdfjs" as  the given command not worked for me, i.e npm install rkusa/pdfjs@2.0.0-alpha.1

**Comment by rkusa** [comment]
Which Node version are you using? Maybe you have to start node with the `--harmony-async-await` flag, if it is not the most recent `7.x` version.

**Comment by barindam** [comment]
My node version is 6.9.1

**Comment by rkusa** [comment]
Sorry, then you have to either update your Node version or run node through babel. (if it works correctly, `npm install pdfjs` should have complained about your Node version)

I could run pdfjs through babel before publishing to NPM, which would add support for Node <7. However, I am not sure if this is still worth the effort with Node 7 supporting async/await natively and since many Node <7 users seem use babel anyway. On the other hand, Node v7 is not LTS, yet. Opinions are welcome.

**Comment by barindam** [comment]
Yes it installed correctly , I got error with the following command:
 npm install rkusa/pdfjs@2.0.0-alpha.1

I also tried  npm install pdfjs@2.0.0-alpha.1, it also installed correctly

**Comment by barindam** [comment]
After updating node version to 7.X the issue resolved.
Closing this issue.
Thanks you very much for the help.
