### ISSUE TITLE
How can we read data from existing pdf file

### ISSUE THREAD

**Issue by duvemula** [rkusa/pdfjs#71]
Hi @rkusa ,

How can we read data from existing pdf file(both normal pdf and pdf image file).

Regards,
Durga Prasad

**Comment by rkusa** [comment]
Hi @duvemula,
what do you try to achieve? `new pdfExternalDocument(src)` parses an external PDF, you could then access the pages through the `pages` object. But these are raw PDF objects without a user-friendly API.

**Comment by duvemula** [comment]
Hi @rkusa ,


I have to read pdf file content and properties(i.e if pdf file have table I need to verify width of table ).

I am using protractor tool with node.js
I tried but I am unable to get it
code snippet:
     var PDFJS = require('pdfjs');
      var buffer = fs.readFileSync(''+filePath+'/Report.pdf')
      var pdfData=  new PDFJS .pdfExternalDocument(buffer)

Would you mind Could you please elaborate more.

Regards,
Durga Prasad

**Comment by rkusa** [comment]
> if pdf file have table I need to verify width of table

This is very difficult to do. `pdfjs` only gives you raw access to the content of the PDF, which means you have data streams like:

```
BT
1.000 0.000 0.000 1.000 201.765 796.817 Tm
10.175 TL
/F1 11.000 Tf
0.000 0.000 0.000 sc
(Lorem ipsum dolor sit amet, consetetur ) Tj
12.452 TL
T*
(sadipscing elitr, sed diam nonumy ) Tj
T*
(eirmod tempor invidunt ut labore et ) Tj
T*
(dolore magna aliquyam erat, sed diam ) Tj
T*
(voluptua. At vero eos et accusam et ) Tj
T*
ET
/CS1 CS
/CS1 cs
q
0.933 0.933 0.933 sc
10.000 171.940 191.765 635.051 re
f
Q
```

These streams contain operations like write text at coord `x/y`, draw rectangle at `...`, fill rectangle with color `...` etc.
There is nothing simple that lets you detect a table, because a table is just a bunch of draw calls in the PDF's coordinate system. There are some PDFs that have some additional content describing the semantic of each area in the PDF but this is nothing one could rely on to determine tables for all kinds of PDFs.

I am afraid that `pdfjs` does not help your use case unless you are willing to write a table detection yourself 😕
